// Generated by CoffeeScript 1.6.3
(function() {
  var requirejs;

  requirejs = require('requirejs');

  requirejs.config({
    baseUrl: __dirname,
    nodeRequire: require
  });

  requirejs(['expect.js'], function(expect) {
    console.log("test");
    return describe("Main test", function() {
      return describe("Messages", function() {
        return it("should have an id", function() {
          var message;
          message = new Message();
          expect(message.id).to.not.throwException();
          expect(message.id).to.be.a('number');
          return expect(message.id).to.eql(parseInt(message.id));
        });
      });
    });
  });

}).call(this);
