// Generated by CoffeeScript 1.6.3
var Message, expect;

expect = require('expect.js');

Message = require('../lib/model/message');

describe("Main test", function() {
  return describe("Messages", function() {
    return it("should have an id", function() {
      var message;
      message = new Message();
      console.log(message.getId());
      expect(message.id).to.not.throwException();
      expect(message.id).to.be.a('number');
      return expect(message.id).to.eql(parseInt(message.id));
    });
  });
});
