// Generated by CoffeeScript 1.6.3
(function() {
  var requirejs;

  requirejs = require('requirejs');

  requirejs.config({
    baseUrl: __dirname,
    nodeRequire: require
  });

  requirejs(['expect.js', 'lib/model/message'], function(expect, Message) {
    return suite('Message', function() {
      return suite('constructor', function() {
        return test('message should have an id', function() {
          var message;
          message = new Message();
          expect(message.id).to.not.throwException();
          expect(message.id).to.be.a('number');
          return expect(message.id).to.eql(parseInt(message.id));
        });
      });
    });
  });

}).call(this);
