// Generated by CoffeeScript 1.6.3
var Message, expect;

expect = require('expect.js');

Message = require('../../lib/model/message');

describe("Behavior", function() {
  return describe("Connection", function() {
    it("should connect", function() {});
    it("should receive a connect ack", function() {});
    return it("should disconnect", function() {});
  });
});
