// Generated by CoffeeScript 1.6.3
var Message, MessageException;

MessageException = (function() {
  function MessageException(message) {
    this.message = message;
    this.name = 'MessageException';
  }

  return MessageException;

})();

Message = (function() {
  Message.id = 0;

  function Message() {
    this.internalId = Message.id++;
    this.type = '';
    this.command = '';
    this.document = {};
    this.timestamp = new Date();
  }

  Message.prototype.getId = function() {
    return this.internalId;
  };

  Message.prototype.getType = function() {
    return this.type;
  };

  Message.prototype.setType = function(type) {
    this.type = type;
  };

  Message.prototype.getCommand = function() {
    return this.command;
  };

  Message.prototype.setCommand = function(command) {
    this.command = command;
  };

  Message.prototype.getDocument = function() {
    return this.document;
  };

  Message.prototype.setDocument = function(doc) {
    if (typeof doc === 'object') {
      return this.document = doc;
    } else {
      throw new MessageException("message document must be an object");
    }
  };

  Message.prototype.getTimestamp = function() {
    return this.timestamp;
  };

  return Message;

})();

module.exports = Message;
