// Generated by CoffeeScript 1.6.3
var Message;

Message = (function() {
  function Message() {
    this.id = 1;
  }

  Message.prototype.getId = function() {
    return this.id;
  };

  return Message;

})();

module.exports = Message;
