// Generated by CoffeeScript 1.6.3
var Message;

Message = (function() {
  Message.id = 0;

  function Message() {
    this.internalId = Message.id++;
  }

  Message.prototype.getId = function() {
    return this.internalId;
  };

  return Message;

})();

module.exports = Message;
